set -g tmate-server-host "a7d217eefb0cc45559c2a51bccf39352-988989726.eu-west-1.elb.amazonaws.com"
set -g tmate-server-port 22
set -g tmate-server-rsa-fingerprint     "SHA256:DD0eeP1fuUZX7dx4V7p5BFi6OoW1N9j5+BCU60teNDc"
set -g tmate-server-ed25519-fingerprint "SHA256:Z2dlSheR6fTi0qoFhxwkTdzrDNM4+/zZvlDQdUjfC78"
